[2024-08-08T09:08:06.841+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T09:08:06.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.entrenamiento manual__2024-08-07T16:19:54.555761+00:00 [queued]>
[2024-08-08T09:08:06.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.entrenamiento manual__2024-08-07T16:19:54.555761+00:00 [queued]>
[2024-08-08T09:08:06.861+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-08-08T09:08:06.872+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): entrenamiento> on 2024-08-07 16:19:54.555761+00:00
[2024-08-08T09:08:06.878+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=354) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-08T09:08:06.879+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'entrenamiento', 'manual__2024-08-07T16:19:54.555761+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmphfg69_mx']
[2024-08-08T09:08:06.879+0000] {standard_task_runner.py:64} INFO - Started process 367 to run task
[2024-08-08T09:08:06.879+0000] {standard_task_runner.py:91} INFO - Job 207: Subtask entrenamiento
[2024-08-08T09:08:06.911+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.entrenamiento manual__2024-08-07T16:19:54.555761+00:00 [running]> on host 2e0aa47c11fb
[2024-08-08T09:08:06.966+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='entrenamiento' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T16:19:54.555761+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T16:19:54.555761+00:00'
[2024-08-08T09:08:06.967+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T09:08:06.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T09:08:06.974+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_prueba_tecnica.py", line 70, in entrenamientoDatos
    df_normado =  pd.read_json(data)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 780, in read_json
    json_reader = JsonReader(
                  ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 893, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 933, in _get_data_from_filepath
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 460, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-08-08T09:08:06.981+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_prueba_tecnica, task_id=entrenamiento, run_id=manual__2024-08-07T16:19:54.555761+00:00, execution_date=20240807T161954, start_date=20240808T090806, end_date=20240808T090806
[2024-08-08T09:08:06.990+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 207 for task entrenamiento (Invalid file path or buffer object type: <class 'NoneType'>; 367)
[2024-08-08T09:08:07.012+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-08T09:08:07.023+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T09:08:07.027+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
