[2024-08-08T09:27:41.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T09:27:41.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:27:19.569952+00:00 [queued]>
[2024-08-08T09:27:41.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:27:19.569952+00:00 [queued]>
[2024-08-08T09:27:41.940+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-08T09:27:41.958+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): limpieza> on 2024-08-08 09:27:19.569952+00:00
[2024-08-08T09:27:41.966+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'limpieza', 'manual__2024-08-08T09:27:19.569952+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmp9xf7hzr2']
[2024-08-08T09:27:41.967+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-08T09:27:41.967+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask limpieza
[2024-08-08T09:27:41.967+0000] {standard_task_runner.py:64} INFO - Started process 115 to run task
[2024-08-08T09:27:42.003+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:27:19.569952+00:00 [running]> on host 9fb498cdebb0
[2024-08-08T09:27:42.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='limpieza' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T09:27:19.569952+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-08T09:27:19.569952+00:00'
[2024-08-08T09:27:42.066+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T09:27:45.264+0000] {warnings.py:112} WARNING - /opt/***/dags/dag_prueba_tecnica.py:41: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient='records')

[2024-08-08T09:27:55.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T09:27:55.719+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_prueba_tecnica.py", line 63, in limpiezaDatos
    df_normado.to_sql('customers', pg_hook.get_sqlalchemy_engine(), if_exists='replace')
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 245, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-08-08T09:27:55.722+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_prueba_tecnica, task_id=limpieza, run_id=manual__2024-08-08T09:27:19.569952+00:00, execution_date=20240808T092719, start_date=20240808T092741, end_date=20240808T092755
[2024-08-08T09:27:55.737+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task limpieza (The conn_id `postgres_localhost` isn't defined; 115)
[2024-08-08T09:27:55.840+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-08T09:27:55.853+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T09:27:55.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
